### ISSUE TITLE
docs: add markdown plugin to README

### ISSUE THREAD

**Issue by peterpeterparker** [papyrs/papyrs#11]
### Feature Description

We've got a cool Chrome markdown-plugin ([repo](https://github.com/papyrs/markdown-plugin) - [web store](https://chrome.google.com/webstore/detail/papyrs-to-markdown/caacmbgdcjpdpmccocmbiljodkbkjglh)) that can be use to convert a blog post to markdown but it isn't yet referenced in this README. Would probably be nice to mention it.

**Comment by SohamRatnaparkhi** [comment]
Hi, I am looking forward to solving the issue.
