### ISSUE TITLE
nested list is breaking the editor UI

### ISSUE THREAD

**Issue by rahultrivedi180** [papyrs/papyrs#35]
### Expected Behavior

Nested list should have some limits in my opinion. If not, it should at least not break the editor UI.

### Actual Behavior

Nested list does not have any limit and that is also causing UI issues in the editor. 

### Reproduction

Steps to reproduce:

1. Keep nesting the list in the editor

### Screenshots

https://user-images.githubusercontent.com/32861078/181717375-c27b3147-d723-476d-b347-dad2a46127e5.mp4

### Environment

- Browser(s): Chrome (Latest version)
- Operating System (e.g. Windows, macOS, Ubuntu): Pop!_OS 22.04

**Comment by peterpeterparker** [comment]
Thanks!
